"""Google Pay MCP Server implemented with FastMCP.

This server exposes utility tools for validating and handling Google Pay style
payloads for local development and testing.
"""

from __future__ import annotations

import base64
import hashlib
import json
from datetime import datetime, timezone
from typing import Any

from mcp.server.fastmcp import FastMCP


class GooglePayFastMCPServer:
    """Google Pay helper tools hosted via FastMCP."""

    def __init__(self) -> None:
        self.app = FastMCP("google-pay-mcp-server")
        self._register_tools()

    def _register_tools(self) -> None:
        @self.app.tool()
        def health() -> dict[str, Any]:
            """Return basic health metadata for the server."""
            return {
                "status": "ok",
                "service": "google-pay-mcp-server",
                "timestamp": datetime.now(timezone.utc).isoformat(),
            }

        @self.app.tool()
        def validate_payment_payload(payload: str) -> dict[str, Any]:
            """Validate a Google Pay-style JSON payload.

            Args:
                payload: Raw JSON string representing paymentData from Google Pay.
            """
            try:
                data = json.loads(payload)
            except json.JSONDecodeError as exc:
                return {"valid": False, "errors": [f"Invalid JSON: {exc.msg}"]}

            required_paths = [
                "apiVersion",
                "apiVersionMinor",
                "paymentMethodData.type",
                "paymentMethodData.description",
                "paymentMethodData.tokenizationData.type",
                "paymentMethodData.tokenizationData.token",
            ]

            errors: list[str] = []
            for path in required_paths:
                if _get_nested(data, path.split(".")) is None:
                    errors.append(f"Missing required field: {path}")

            return {
                "valid": len(errors) == 0,
                "errors": errors,
                "network": _get_nested(
                    data, ["paymentMethodData", "info", "cardNetwork"]
                ),
                "last4": _get_nested(data, ["paymentMethodData", "info", "cardDetails"]),
            }

        @self.app.tool()
        def create_test_payment_token(
            merchant_id: str,
            amount: str,
            currency_code: str,
            payment_reference: str,
        ) -> dict[str, str]:
            """Create a deterministic test token for non-production workflows."""
            raw = f"{merchant_id}|{amount}|{currency_code}|{payment_reference}"
            digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()
            token = base64.urlsafe_b64encode(digest.encode("utf-8")).decode("utf-8")
            return {
                "token": token,
                "token_type": "TEST_GATEWAY_TOKEN",
                "merchant_id": merchant_id,
            }

        @self.app.tool()
        def decode_test_payment_token(token: str) -> dict[str, Any]:
            """Decode a token generated by create_test_payment_token."""
            try:
                decoded = base64.urlsafe_b64decode(token.encode("utf-8")).decode("utf-8")
            except Exception:
                return {"ok": False, "error": "Token is not a valid test token"}

            if len(decoded) != 64:
                return {"ok": False, "error": "Unexpected token length"}

            return {"ok": True, "sha256_hex": decoded}


    def run(self) -> None:
        """Run the FastMCP server over stdio transport."""
        self.app.run(transport="stdio")


def _get_nested(data: dict[str, Any], path: list[str]) -> Any:
    current: Any = data
    for key in path:
        if not isinstance(current, dict) or key not in current:
            return None
        current = current[key]
    return current


if __name__ == "__main__":
    GooglePayFastMCPServer().run()
